name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 13

  docker:
  
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build
      run: mvn -B package --file pom.xml
        
    - name: Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: farukaydin7/user-service
        tags: latest
        registry: docker.io
        dockerfile: src/main/docker/Dockerfile.jvm
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
